dist: trusty

language: R
r:
  - release
  - devel

warnings_are_errors: false
sudo: required

apt_packages:
  - libgsl-dev
  - libcurl4-openssl-dev
  - libxml2-dev

before_install:
  - sudo add-apt-repository ppa:marutter/c2d4u -y
  - sudo apt-get update -q

repos:
  CRAN: http://cran.rstudio.com
